name: 'Add quarter label to my event'
description: 'Checks the name of an Issue and adds quarter label'
inputs:
  token:  # id of input
    description: 'GitHub token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
